// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: alarm/alarm.proto

package alarm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlarmLevel int32

const (
	AlarmLevel_ALARM_LEVEL_UNSPECIFIED AlarmLevel = 0
	AlarmLevel_INFO                    AlarmLevel = 1
	AlarmLevel_WARN                    AlarmLevel = 2
	AlarmLevel_CRITICAL                AlarmLevel = 3
	AlarmLevel_FATAL                   AlarmLevel = 4
)

// Enum value maps for AlarmLevel.
var (
	AlarmLevel_name = map[int32]string{
		0: "ALARM_LEVEL_UNSPECIFIED",
		1: "INFO",
		2: "WARN",
		3: "CRITICAL",
		4: "FATAL",
	}
	AlarmLevel_value = map[string]int32{
		"ALARM_LEVEL_UNSPECIFIED": 0,
		"INFO":                    1,
		"WARN":                    2,
		"CRITICAL":                3,
		"FATAL":                   4,
	}
)

func (x AlarmLevel) Enum() *AlarmLevel {
	p := new(AlarmLevel)
	*p = x
	return p
}

func (x AlarmLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlarmLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_alarm_alarm_proto_enumTypes[0].Descriptor()
}

func (AlarmLevel) Type() protoreflect.EnumType {
	return &file_alarm_alarm_proto_enumTypes[0]
}

func (x AlarmLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlarmLevel.Descriptor instead.
func (AlarmLevel) EnumDescriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{0}
}

type AlarmReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	DeviceCode    string                 `protobuf:"bytes,2,opt,name=deviceCode,proto3" json:"deviceCode,omitempty"`
	GatewayCode   string                 `protobuf:"bytes,3,opt,name=gatewayCode,proto3" json:"gatewayCode,omitempty"`
	AlarmId       string                 `protobuf:"bytes,4,opt,name=alarmId,proto3" json:"alarmId,omitempty"`
	Level         AlarmLevel             `protobuf:"varint,5,opt,name=level,proto3,enum=alarm.AlarmLevel" json:"level,omitempty"`
	IsRecovery    bool                   `protobuf:"varint,6,opt,name=isRecovery,proto3" json:"isRecovery,omitempty"`
	Msg           string                 `protobuf:"bytes,7,opt,name=msg,proto3" json:"msg,omitempty"`
	Threshold     string                 `protobuf:"bytes,8,opt,name=threshold,proto3" json:"threshold,omitempty"`
	CurrentValue  string                 `protobuf:"bytes,9,opt,name=currentValue,proto3" json:"currentValue,omitempty"`
	PointCode     string                 `protobuf:"bytes,10,opt,name=pointCode,proto3" json:"pointCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmReportRequest) Reset() {
	*x = AlarmReportRequest{}
	mi := &file_alarm_alarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmReportRequest) ProtoMessage() {}

func (x *AlarmReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmReportRequest.ProtoReflect.Descriptor instead.
func (*AlarmReportRequest) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmReportRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AlarmReportRequest) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *AlarmReportRequest) GetGatewayCode() string {
	if x != nil {
		return x.GatewayCode
	}
	return ""
}

func (x *AlarmReportRequest) GetAlarmId() string {
	if x != nil {
		return x.AlarmId
	}
	return ""
}

func (x *AlarmReportRequest) GetLevel() AlarmLevel {
	if x != nil {
		return x.Level
	}
	return AlarmLevel_ALARM_LEVEL_UNSPECIFIED
}

func (x *AlarmReportRequest) GetIsRecovery() bool {
	if x != nil {
		return x.IsRecovery
	}
	return false
}

func (x *AlarmReportRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AlarmReportRequest) GetThreshold() string {
	if x != nil {
		return x.Threshold
	}
	return ""
}

func (x *AlarmReportRequest) GetCurrentValue() string {
	if x != nil {
		return x.CurrentValue
	}
	return ""
}

func (x *AlarmReportRequest) GetPointCode() string {
	if x != nil {
		return x.PointCode
	}
	return ""
}

type AlarmReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmReportResponse) Reset() {
	*x = AlarmReportResponse{}
	mi := &file_alarm_alarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmReportResponse) ProtoMessage() {}

func (x *AlarmReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmReportResponse.ProtoReflect.Descriptor instead.
func (*AlarmReportResponse) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{1}
}

func (x *AlarmReportResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AlarmReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AlarmReportResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AlarmReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BatchAlarmReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	GatewayCode   string                 `protobuf:"bytes,2,opt,name=gatewayCode,proto3" json:"gatewayCode,omitempty"`
	DriverCode    string                 `protobuf:"bytes,3,opt,name=driverCode,proto3" json:"driverCode,omitempty"`
	Alarms        []*AlarmReportRequest  `protobuf:"bytes,4,rep,name=alarms,proto3" json:"alarms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAlarmReportRequest) Reset() {
	*x = BatchAlarmReportRequest{}
	mi := &file_alarm_alarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAlarmReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAlarmReportRequest) ProtoMessage() {}

func (x *BatchAlarmReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAlarmReportRequest.ProtoReflect.Descriptor instead.
func (*BatchAlarmReportRequest) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{2}
}

func (x *BatchAlarmReportRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BatchAlarmReportRequest) GetGatewayCode() string {
	if x != nil {
		return x.GatewayCode
	}
	return ""
}

func (x *BatchAlarmReportRequest) GetDriverCode() string {
	if x != nil {
		return x.DriverCode
	}
	return ""
}

func (x *BatchAlarmReportRequest) GetAlarms() []*AlarmReportRequest {
	if x != nil {
		return x.Alarms
	}
	return nil
}

type BatchAlarmReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchAlarmReportResponse) Reset() {
	*x = BatchAlarmReportResponse{}
	mi := &file_alarm_alarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchAlarmReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchAlarmReportResponse) ProtoMessage() {}

func (x *BatchAlarmReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alarm_alarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchAlarmReportResponse.ProtoReflect.Descriptor instead.
func (*BatchAlarmReportResponse) Descriptor() ([]byte, []int) {
	return file_alarm_alarm_proto_rawDescGZIP(), []int{3}
}

func (x *BatchAlarmReportResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *BatchAlarmReportResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *BatchAlarmReportResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BatchAlarmReportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_alarm_alarm_proto protoreflect.FileDescriptor

const file_alarm_alarm_proto_rawDesc = "" +
	"\n" +
	"\x11alarm/alarm.proto\x12\x05alarm\"\xc5\x02\n" +
	"\x12AlarmReportRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"deviceCode\x18\x02 \x01(\tR\n" +
	"deviceCode\x12 \n" +
	"\vgatewayCode\x18\x03 \x01(\tR\vgatewayCode\x12\x18\n" +
	"\aalarmId\x18\x04 \x01(\tR\aalarmId\x12'\n" +
	"\x05level\x18\x05 \x01(\x0e2\x11.alarm.AlarmLevelR\x05level\x12\x1e\n" +
	"\n" +
	"isRecovery\x18\x06 \x01(\bR\n" +
	"isRecovery\x12\x10\n" +
	"\x03msg\x18\a \x01(\tR\x03msg\x12\x1c\n" +
	"\tthreshold\x18\b \x01(\tR\tthreshold\x12\"\n" +
	"\fcurrentValue\x18\t \x01(\tR\fcurrentValue\x12\x1c\n" +
	"\tpointCode\x18\n" +
	" \x01(\tR\tpointCode\"o\n" +
	"\x13AlarmReportResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xa8\x01\n" +
	"\x17BatchAlarmReportRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12 \n" +
	"\vgatewayCode\x18\x02 \x01(\tR\vgatewayCode\x12\x1e\n" +
	"\n" +
	"driverCode\x18\x03 \x01(\tR\n" +
	"driverCode\x121\n" +
	"\x06alarms\x18\x04 \x03(\v2\x19.alarm.AlarmReportRequestR\x06alarms\"t\n" +
	"\x18BatchAlarmReportResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess*V\n" +
	"\n" +
	"AlarmLevel\x12\x1b\n" +
	"\x17ALARM_LEVEL_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\b\n" +
	"\x04WARN\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03\x12\t\n" +
	"\x05FATAL\x10\x042\xad\x01\n" +
	"\fAlarmService\x12F\n" +
	"\vReportAlarm\x12\x19.alarm.AlarmReportRequest\x1a\x1a.alarm.AlarmReportResponse\"\x00\x12U\n" +
	"\x10BatchReportAlarm\x12\x1e.alarm.BatchAlarmReportRequest\x1a\x1f.alarm.BatchAlarmReportResponse\"\x00B~\n" +
	"\tcom.alarmB\n" +
	"AlarmProtoP\x01Z1github.com/lostvip-com/lv_grpc_driver_proto/alarm\xa2\x02\x03AXX\xaa\x02\x05Alarm\xca\x02\x05Alarm\xe2\x02\x11Alarm\\GPBMetadata\xea\x02\x05Alarmb\x06proto3"

var (
	file_alarm_alarm_proto_rawDescOnce sync.Once
	file_alarm_alarm_proto_rawDescData []byte
)

func file_alarm_alarm_proto_rawDescGZIP() []byte {
	file_alarm_alarm_proto_rawDescOnce.Do(func() {
		file_alarm_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alarm_alarm_proto_rawDesc), len(file_alarm_alarm_proto_rawDesc)))
	})
	return file_alarm_alarm_proto_rawDescData
}

var file_alarm_alarm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alarm_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_alarm_alarm_proto_goTypes = []any{
	(AlarmLevel)(0),                  // 0: alarm.AlarmLevel
	(*AlarmReportRequest)(nil),       // 1: alarm.AlarmReportRequest
	(*AlarmReportResponse)(nil),      // 2: alarm.AlarmReportResponse
	(*BatchAlarmReportRequest)(nil),  // 3: alarm.BatchAlarmReportRequest
	(*BatchAlarmReportResponse)(nil), // 4: alarm.BatchAlarmReportResponse
}
var file_alarm_alarm_proto_depIdxs = []int32{
	0, // 0: alarm.AlarmReportRequest.level:type_name -> alarm.AlarmLevel
	1, // 1: alarm.BatchAlarmReportRequest.alarms:type_name -> alarm.AlarmReportRequest
	1, // 2: alarm.AlarmService.ReportAlarm:input_type -> alarm.AlarmReportRequest
	3, // 3: alarm.AlarmService.BatchReportAlarm:input_type -> alarm.BatchAlarmReportRequest
	2, // 4: alarm.AlarmService.ReportAlarm:output_type -> alarm.AlarmReportResponse
	4, // 5: alarm.AlarmService.BatchReportAlarm:output_type -> alarm.BatchAlarmReportResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alarm_alarm_proto_init() }
func file_alarm_alarm_proto_init() {
	if File_alarm_alarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alarm_alarm_proto_rawDesc), len(file_alarm_alarm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alarm_alarm_proto_goTypes,
		DependencyIndexes: file_alarm_alarm_proto_depIdxs,
		EnumInfos:         file_alarm_alarm_proto_enumTypes,
		MessageInfos:      file_alarm_alarm_proto_msgTypes,
	}.Build()
	File_alarm_alarm_proto = out.File
	file_alarm_alarm_proto_goTypes = nil
	file_alarm_alarm_proto_depIdxs = nil
}
