// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	AccessMode    string                 `protobuf:"bytes,6,opt,name=accessMode,proto3" json:"accessMode,omitempty"`
	DataType      string                 `protobuf:"bytes,7,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Unit          string                 `protobuf:"bytes,9,opt,name=unit,proto3" json:"unit,omitempty"`
	Extra         string                 `protobuf:"bytes,10,opt,name=extra,proto3" json:"extra,omitempty"`
	Remark        string                 `protobuf:"bytes,11,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Property) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Property) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Property) GetAccessMode() string {
	if x != nil {
		return x.AccessMode
	}
	return ""
}

func (x *Property) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Property) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Property) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Property) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	CallType      string                 `protobuf:"bytes,6,opt,name=callType,proto3" json:"callType,omitempty"`
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *Action) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Action) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Action) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Action) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Action) GetCallType() string {
	if x != nil {
		return x.CallType
	}
	return ""
}

func (x *Action) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Action) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=productId,proto3" json:"productId,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Tag           string                 `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Event) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Event) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type LoadThingModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	ProductCode   string                 `protobuf:"bytes,2,opt,name=productCode,proto3" json:"productCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadThingModelRequest) Reset() {
	*x = LoadThingModelRequest{}
	mi := &file_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadThingModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadThingModelRequest) ProtoMessage() {}

func (x *LoadThingModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadThingModelRequest.ProtoReflect.Descriptor instead.
func (*LoadThingModelRequest) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *LoadThingModelRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LoadThingModelRequest) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

type LoadThingModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	Properties    []*Property            `protobuf:"bytes,7,rep,name=properties,proto3" json:"properties,omitempty"`
	Actions       []*Action              `protobuf:"bytes,8,rep,name=actions,proto3" json:"actions,omitempty"`
	Events        []*Event               `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadThingModelResponse) Reset() {
	*x = LoadThingModelResponse{}
	mi := &file_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadThingModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadThingModelResponse) ProtoMessage() {}

func (x *LoadThingModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadThingModelResponse.ProtoReflect.Descriptor instead.
func (*LoadThingModelResponse) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *LoadThingModelResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LoadThingModelResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LoadThingModelResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoadThingModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoadThingModelResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadThingModelResponse) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *LoadThingModelResponse) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *LoadThingModelResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *LoadThingModelResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_product_product_proto protoreflect.FileDescriptor

const file_product_product_proto_rawDesc = "" +
	"\n" +
	"\x15product/product.proto\x12\aproduct\"\xf0\x01\n" +
	"\bProperty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x1e\n" +
	"\n" +
	"accessMode\x18\x06 \x01(\tR\n" +
	"accessMode\x12\x1a\n" +
	"\bdataType\x18\a \x01(\tR\bdataType\x12\x12\n" +
	"\x04unit\x18\t \x01(\tR\x04unit\x12\x14\n" +
	"\x05extra\x18\n" +
	" \x01(\tR\x05extra\x12\x16\n" +
	"\x06remark\x18\v \x01(\tR\x06remark\"\xba\x01\n" +
	"\x06Action\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1a\n" +
	"\bcallType\x18\x06 \x01(\tR\bcallType\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"\xbb\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tproductId\x18\x02 \x01(\x03R\tproductId\x12\x1c\n" +
	"\teventType\x18\x03 \x01(\tR\teventType\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x10\n" +
	"\x03tag\x18\x05 \x01(\tR\x03tag\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\"S\n" +
	"\x15LoadThingModelRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12 \n" +
	"\vproductCode\x18\x02 \x01(\tR\vproductCode\"\xa2\x02\n" +
	"\x16LoadThingModelResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\x121\n" +
	"\n" +
	"properties\x18\a \x03(\v2\x11.product.PropertyR\n" +
	"properties\x12)\n" +
	"\aactions\x18\b \x03(\v2\x0f.product.ActionR\aactions\x12&\n" +
	"\x06events\x18\t \x03(\v2\x0e.product.EventR\x06events2a\n" +
	"\n" +
	"RpcProduct\x12S\n" +
	"\x0eLoadThingModel\x12\x1e.product.LoadThingModelRequest\x1a\x1f.product.LoadThingModelResponse\"\x00B\x8c\x01\n" +
	"\vcom.productB\fProductProtoP\x01Z3github.com/lostvip-com/lv_grpc_driver_proto/product\xa2\x02\x03PXX\xaa\x02\aProduct\xca\x02\aProduct\xe2\x02\x13Product\\GPBMetadata\xea\x02\aProductb\x06proto3"

var (
	file_product_product_proto_rawDescOnce sync.Once
	file_product_product_proto_rawDescData []byte
)

func file_product_product_proto_rawDescGZIP() []byte {
	file_product_product_proto_rawDescOnce.Do(func() {
		file_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)))
	})
	return file_product_product_proto_rawDescData
}

var file_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_product_proto_goTypes = []any{
	(*Property)(nil),               // 0: product.Property
	(*Action)(nil),                 // 1: product.Action
	(*Event)(nil),                  // 2: product.Event
	(*LoadThingModelRequest)(nil),  // 3: product.LoadThingModelRequest
	(*LoadThingModelResponse)(nil), // 4: product.LoadThingModelResponse
}
var file_product_product_proto_depIdxs = []int32{
	0, // 0: product.LoadThingModelResponse.properties:type_name -> product.Property
	1, // 1: product.LoadThingModelResponse.actions:type_name -> product.Action
	2, // 2: product.LoadThingModelResponse.events:type_name -> product.Event
	3, // 3: product.RpcProduct.LoadThingModel:input_type -> product.LoadThingModelRequest
	4, // 4: product.RpcProduct.LoadThingModel:output_type -> product.LoadThingModelResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_product_product_proto_init() }
func file_product_product_proto_init() {
	if File_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_proto_goTypes,
		DependencyIndexes: file_product_product_proto_depIdxs,
		MessageInfos:      file_product_product_proto_msgTypes,
	}.Build()
	File_product_product_proto = out.File
	file_product_product_proto_goTypes = nil
	file_product_product_proto_depIdxs = nil
}
