// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: product.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcProduct_LoadThingModel_FullMethodName = "/product.RpcProduct/LoadThingModel"
)

// RpcProductClient is the client API for RpcProduct service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcProductClient interface {
	LoadThingModel(ctx context.Context, in *LoadThingModelRequest, opts ...grpc.CallOption) (*LoadThingModelResponse, error)
}

type rpcProductClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcProductClient(cc grpc.ClientConnInterface) RpcProductClient {
	return &rpcProductClient{cc}
}

func (c *rpcProductClient) LoadThingModel(ctx context.Context, in *LoadThingModelRequest, opts ...grpc.CallOption) (*LoadThingModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadThingModelResponse)
	err := c.cc.Invoke(ctx, RpcProduct_LoadThingModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcProductServer is the server API for RpcProduct service.
// All implementations must embed UnimplementedRpcProductServer
// for forward compatibility.
type RpcProductServer interface {
	LoadThingModel(context.Context, *LoadThingModelRequest) (*LoadThingModelResponse, error)
	mustEmbedUnimplementedRpcProductServer()
}

// UnimplementedRpcProductServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcProductServer struct{}

func (UnimplementedRpcProductServer) LoadThingModel(context.Context, *LoadThingModelRequest) (*LoadThingModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadThingModel not implemented")
}
func (UnimplementedRpcProductServer) mustEmbedUnimplementedRpcProductServer() {}
func (UnimplementedRpcProductServer) testEmbeddedByValue()                    {}

// UnsafeRpcProductServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcProductServer will
// result in compilation errors.
type UnsafeRpcProductServer interface {
	mustEmbedUnimplementedRpcProductServer()
}

func RegisterRpcProductServer(s grpc.ServiceRegistrar, srv RpcProductServer) {
	// If the following call panics, it indicates UnimplementedRpcProductServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcProduct_ServiceDesc, srv)
}

func _RpcProduct_LoadThingModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadThingModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcProductServer).LoadThingModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcProduct_LoadThingModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcProductServer).LoadThingModel(ctx, req.(*LoadThingModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcProduct_ServiceDesc is the grpc.ServiceDesc for RpcProduct service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcProduct_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product.RpcProduct",
	HandlerType: (*RpcProductServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LoadThingModel",
			Handler:    _RpcProduct_LoadThingModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
