// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: data/data.proto

package data

import (
	device "github.com/lostvip-com/lv_grpc_driver_proto/device"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_UNSPECIFIED                      OperationType = 0
	OperationType_PROPERTY_SET                     OperationType = 1
	OperationType_PROPERTY_GET                     OperationType = 2
	OperationType_SERVICE_EXECUTE                  OperationType = 3
	OperationType_PROPERTY_REPORT_RESPONSE         OperationType = 4
	OperationType_EVENT_REPORT_RESPONSE            OperationType = 5
	OperationType_DATA_BATCH_REPORT_RESPONSE       OperationType = 6
	OperationType_PROPERTY_DESIRED_GET_RESPONSE    OperationType = 7
	OperationType_PROPERTY_DESIRED_DELETE_RESPONSE OperationType = 8
	OperationType_CUSTOM_MQTT_PUBLISH              OperationType = 9
	OperationType_PROPERTY_REPORT                  OperationType = 20
	OperationType_PROPERTY_SET_RESPONSE            OperationType = 21
	OperationType_PROPERTY_GET_RESPONSE            OperationType = 22
	OperationType_SERVICE_EXECUTE_RESPONSE         OperationType = 23
	OperationType_EVENT_REPORT                     OperationType = 24
	OperationType_DATA_BATCH_REPORT                OperationType = 25
	OperationType_PROPERTY_DESIRED_GET             OperationType = 26
	OperationType_PROPERTY_DESIRED_DELETE          OperationType = 27
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "PROPERTY_SET",
		2:  "PROPERTY_GET",
		3:  "SERVICE_EXECUTE",
		4:  "PROPERTY_REPORT_RESPONSE",
		5:  "EVENT_REPORT_RESPONSE",
		6:  "DATA_BATCH_REPORT_RESPONSE",
		7:  "PROPERTY_DESIRED_GET_RESPONSE",
		8:  "PROPERTY_DESIRED_DELETE_RESPONSE",
		9:  "CUSTOM_MQTT_PUBLISH",
		20: "PROPERTY_REPORT",
		21: "PROPERTY_SET_RESPONSE",
		22: "PROPERTY_GET_RESPONSE",
		23: "SERVICE_EXECUTE_RESPONSE",
		24: "EVENT_REPORT",
		25: "DATA_BATCH_REPORT",
		26: "PROPERTY_DESIRED_GET",
		27: "PROPERTY_DESIRED_DELETE",
	}
	OperationType_value = map[string]int32{
		"UNSPECIFIED":                      0,
		"PROPERTY_SET":                     1,
		"PROPERTY_GET":                     2,
		"SERVICE_EXECUTE":                  3,
		"PROPERTY_REPORT_RESPONSE":         4,
		"EVENT_REPORT_RESPONSE":            5,
		"DATA_BATCH_REPORT_RESPONSE":       6,
		"PROPERTY_DESIRED_GET_RESPONSE":    7,
		"PROPERTY_DESIRED_DELETE_RESPONSE": 8,
		"CUSTOM_MQTT_PUBLISH":              9,
		"PROPERTY_REPORT":                  20,
		"PROPERTY_SET_RESPONSE":            21,
		"PROPERTY_GET_RESPONSE":            22,
		"SERVICE_EXECUTE_RESPONSE":         23,
		"EVENT_REPORT":                     24,
		"DATA_BATCH_REPORT":                25,
		"PROPERTY_DESIRED_GET":             26,
		"PROPERTY_DESIRED_DELETE":          27,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_data_data_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_data_data_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	DataType      string                 `protobuf:"bytes,4,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Rate          string                 `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_data_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Point) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Point) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Point) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *Point) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OperationType          `protobuf:"varint,1,opt,name=type,proto3,enum=data.OperationType" json:"type,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=traceId,proto3" json:"traceId,omitempty"`
	GatewayCode   string                 `protobuf:"bytes,3,opt,name=gatewayCode,proto3" json:"gatewayCode,omitempty"`
	DeviceCode    string                 `protobuf:"bytes,4,opt,name=deviceCode,proto3" json:"deviceCode,omitempty"`
	NeedAck       bool                   `protobuf:"varint,5,opt,name=needAck,proto3" json:"needAck,omitempty"`
	Points        []*Point               `protobuf:"bytes,6,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_data_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_UNSPECIFIED
}

func (x *Command) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Command) GetGatewayCode() string {
	if x != nil {
		return x.GatewayCode
	}
	return ""
}

func (x *Command) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *Command) GetNeedAck() bool {
	if x != nil {
		return x.NeedAck
	}
	return false
}

func (x *Command) GetPoints() []*Point {
	if x != nil {
		return x.Points
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverCode    string                 `protobuf:"bytes,1,opt,name=driverCode,proto3" json:"driverCode,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_data_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_data_data_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetDriverCode() string {
	if x != nil {
		return x.DriverCode
	}
	return ""
}

func (x *SubscribeRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_data_data_proto protoreflect.FileDescriptor

const file_data_data_proto_rawDesc = "" +
	"\n" +
	"\x0fdata/data.proto\x12\x04data\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13device/device.proto\"\x91\x01\n" +
	"\x05Point\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12.\n" +
	"\x04time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x1a\n" +
	"\bdataType\x18\x04 \x01(\tR\bdataType\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\tR\x04rate\"\xcd\x01\n" +
	"\aCommand\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.data.OperationTypeR\x04type\x12\x18\n" +
	"\atraceId\x18\x02 \x01(\tR\atraceId\x12 \n" +
	"\vgatewayCode\x18\x03 \x01(\tR\vgatewayCode\x12\x1e\n" +
	"\n" +
	"deviceCode\x18\x04 \x01(\tR\n" +
	"deviceCode\x12\x18\n" +
	"\aneedAck\x18\x05 \x01(\bR\aneedAck\x12#\n" +
	"\x06points\x18\x06 \x03(\v2\v.data.PointR\x06points\"R\n" +
	"\x10SubscribeRequest\x12\x1e\n" +
	"\n" +
	"driverCode\x18\x01 \x01(\tR\n" +
	"driverCode\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId*\xdd\x03\n" +
	"\rOperationType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROPERTY_SET\x10\x01\x12\x10\n" +
	"\fPROPERTY_GET\x10\x02\x12\x13\n" +
	"\x0fSERVICE_EXECUTE\x10\x03\x12\x1c\n" +
	"\x18PROPERTY_REPORT_RESPONSE\x10\x04\x12\x19\n" +
	"\x15EVENT_REPORT_RESPONSE\x10\x05\x12\x1e\n" +
	"\x1aDATA_BATCH_REPORT_RESPONSE\x10\x06\x12!\n" +
	"\x1dPROPERTY_DESIRED_GET_RESPONSE\x10\a\x12$\n" +
	" PROPERTY_DESIRED_DELETE_RESPONSE\x10\b\x12\x17\n" +
	"\x13CUSTOM_MQTT_PUBLISH\x10\t\x12\x13\n" +
	"\x0fPROPERTY_REPORT\x10\x14\x12\x19\n" +
	"\x15PROPERTY_SET_RESPONSE\x10\x15\x12\x19\n" +
	"\x15PROPERTY_GET_RESPONSE\x10\x16\x12\x1c\n" +
	"\x18SERVICE_EXECUTE_RESPONSE\x10\x17\x12\x10\n" +
	"\fEVENT_REPORT\x10\x18\x12\x15\n" +
	"\x11DATA_BATCH_REPORT\x10\x19\x12\x18\n" +
	"\x14PROPERTY_DESIRED_GET\x10\x1a\x12\x1b\n" +
	"\x17PROPERTY_DESIRED_DELETE\x10\x1b2\x9d\x01\n" +
	"\vDataService\x12)\n" +
	"\x04Send\x12\r.data.Command\x1a\x10.device.Response\"\x00\x12+\n" +
	"\x06Report\x12\r.data.Command\x1a\x10.device.Response\"\x00\x126\n" +
	"\tSubscribe\x12\x16.data.SubscribeRequest\x1a\r.data.Command\"\x000\x01Bw\n" +
	"\bcom.dataB\tDataProtoP\x01Z0github.com/lostvip-com/lv_grpc_driver_proto/data\xa2\x02\x03DXX\xaa\x02\x04Data\xca\x02\x04Data\xe2\x02\x10Data\\GPBMetadata\xea\x02\x04Datab\x06proto3"

var (
	file_data_data_proto_rawDescOnce sync.Once
	file_data_data_proto_rawDescData []byte
)

func file_data_data_proto_rawDescGZIP() []byte {
	file_data_data_proto_rawDescOnce.Do(func() {
		file_data_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)))
	})
	return file_data_data_proto_rawDescData
}

var file_data_data_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_data_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_data_proto_goTypes = []any{
	(OperationType)(0),            // 0: data.OperationType
	(*Point)(nil),                 // 1: data.Point
	(*Command)(nil),               // 2: data.Command
	(*SubscribeRequest)(nil),      // 3: data.SubscribeRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*device.Response)(nil),       // 5: device.Response
}
var file_data_data_proto_depIdxs = []int32{
	4, // 0: data.Point.time:type_name -> google.protobuf.Timestamp
	0, // 1: data.Command.type:type_name -> data.OperationType
	1, // 2: data.Command.points:type_name -> data.Point
	2, // 3: data.DataService.Send:input_type -> data.Command
	2, // 4: data.DataService.Report:input_type -> data.Command
	3, // 5: data.DataService.Subscribe:input_type -> data.SubscribeRequest
	5, // 6: data.DataService.Send:output_type -> device.Response
	5, // 7: data.DataService.Report:output_type -> device.Response
	2, // 8: data.DataService.Subscribe:output_type -> data.Command
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_data_data_proto_init() }
func file_data_data_proto_init() {
	if File_data_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_data_proto_rawDesc), len(file_data_data_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_data_proto_goTypes,
		DependencyIndexes: file_data_data_proto_depIdxs,
		EnumInfos:         file_data_data_proto_enumTypes,
		MessageInfos:      file_data_data_proto_msgTypes,
	}.Build()
	File_data_data_proto = out.File
	file_data_data_proto_goTypes = nil
	file_data_data_proto_depIdxs = nil
}
