// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Pong) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *VersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DriverRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	DriverType    string                 `protobuf:"bytes,4,opt,name=driverType,proto3" json:"driverType,omitempty"`
	IotPlatform   string                 `protobuf:"bytes,5,opt,name=iotPlatform,proto3" json:"iotPlatform,omitempty"`
	DriverName    string                 `protobuf:"bytes,6,opt,name=driverName,proto3" json:"driverName,omitempty"`
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegisterRequest) Reset() {
	*x = DriverRegisterRequest{}
	mi := &file_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterRequest) ProtoMessage() {}

func (x *DriverRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterRequest.ProtoReflect.Descriptor instead.
func (*DriverRegisterRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverRegisterRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DriverRegisterRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *DriverRegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DriverRegisterRequest) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *DriverRegisterRequest) GetIotPlatform() string {
	if x != nil {
		return x.IotPlatform
	}
	return ""
}

func (x *DriverRegisterRequest) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DriverRegisterRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type DriverRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	InstanceId    int64                  `protobuf:"varint,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegisterResponse) Reset() {
	*x = DriverRegisterResponse{}
	mi := &file_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegisterResponse) ProtoMessage() {}

func (x *DriverRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegisterResponse.ProtoReflect.Descriptor instead.
func (*DriverRegisterResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *DriverRegisterResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DriverRegisterResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DriverRegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverRegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverRegisterResponse) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *DriverRegisterResponse) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type CloudInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInstanceResponse) Reset() {
	*x = CloudInstanceResponse{}
	mi := &file_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInstanceResponse) ProtoMessage() {}

func (x *CloudInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInstanceResponse.ProtoReflect.Descriptor instead.
func (*CloudInstanceResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *CloudInstanceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CloudInstanceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CloudInstanceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CloudInstanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_driver_driver_proto protoreflect.FileDescriptor

const file_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x13driver/driver.proto\x12\x06driver\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\"+\n" +
	"\x0fVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\xe3\x01\n" +
	"\x15DriverRegisterRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"driverType\x18\x04 \x01(\tR\n" +
	"driverType\x12 \n" +
	"\viotPlatform\x18\x05 \x01(\tR\viotPlatform\x12\x1e\n" +
	"\n" +
	"driverName\x18\x06 \x01(\tR\n" +
	"driverName\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\"\xa8\x01\n" +
	"\x16DriverRegisterResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x05 \x01(\x03R\n" +
	"instanceId\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\"m\n" +
	"\x15CloudInstanceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2v\n" +
	"\x06Common\x12.\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\f.driver.Pong\"\x00\x12<\n" +
	"\aVersion\x12\x16.google.protobuf.Empty\x1a\x17.driver.VersionResponse\"\x002i\n" +
	"\x14CloudInstanceService\x12Q\n" +
	"\x0eDriverRegister\x12\x1d.driver.DriverRegisterRequest\x1a\x1e.driver.DriverRegisterResponse\"\x00B\x85\x01\n" +
	"\n" +
	"com.driverB\vDriverProtoP\x01Z2github.com/lostvip-com/lv_grpc_driver_proto/driver\xa2\x02\x03DXX\xaa\x02\x06Driver\xca\x02\x06Driver\xe2\x02\x12Driver\\GPBMetadata\xea\x02\x06Driverb\x06proto3"

var (
	file_driver_driver_proto_rawDescOnce sync.Once
	file_driver_driver_proto_rawDescData []byte
)

func file_driver_driver_proto_rawDescGZIP() []byte {
	file_driver_driver_proto_rawDescOnce.Do(func() {
		file_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)))
	})
	return file_driver_driver_proto_rawDescData
}

var file_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_driver_driver_proto_goTypes = []any{
	(*Pong)(nil),                   // 0: driver.Pong
	(*VersionResponse)(nil),        // 1: driver.VersionResponse
	(*DriverRegisterRequest)(nil),  // 2: driver.DriverRegisterRequest
	(*DriverRegisterResponse)(nil), // 3: driver.DriverRegisterResponse
	(*CloudInstanceResponse)(nil),  // 4: driver.CloudInstanceResponse
	(*emptypb.Empty)(nil),          // 5: google.protobuf.Empty
}
var file_driver_driver_proto_depIdxs = []int32{
	5, // 0: driver.Common.Ping:input_type -> google.protobuf.Empty
	5, // 1: driver.Common.Version:input_type -> google.protobuf.Empty
	2, // 2: driver.CloudInstanceService.DriverRegister:input_type -> driver.DriverRegisterRequest
	0, // 3: driver.Common.Ping:output_type -> driver.Pong
	1, // 4: driver.Common.Version:output_type -> driver.VersionResponse
	3, // 5: driver.CloudInstanceService.DriverRegister:output_type -> driver.DriverRegisterResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_driver_driver_proto_init() }
func file_driver_driver_proto_init() {
	if File_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_driver_driver_proto_goTypes,
		DependencyIndexes: file_driver_driver_proto_depIdxs,
		MessageInfos:      file_driver_driver_proto_msgTypes,
	}.Build()
	File_driver_driver_proto = out.File
	file_driver_driver_proto_goTypes = nil
	file_driver_driver_proto_depIdxs = nil
}
