// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.2
// source: driver/driver.proto

package driver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Common_Ping_FullMethodName = "/driver.Common/Ping"
)

// CommonClient is the client API for Common service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommonClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pong, error)
}

type commonClient struct {
	cc grpc.ClientConnInterface
}

func NewCommonClient(cc grpc.ClientConnInterface) CommonClient {
	return &commonClient{cc}
}

func (c *commonClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Pong, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Pong)
	err := c.cc.Invoke(ctx, Common_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommonServer is the server API for Common service.
// All implementations must embed UnimplementedCommonServer
// for forward compatibility.
type CommonServer interface {
	Ping(context.Context, *emptypb.Empty) (*Pong, error)
	mustEmbedUnimplementedCommonServer()
}

// UnimplementedCommonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommonServer struct{}

func (UnimplementedCommonServer) Ping(context.Context, *emptypb.Empty) (*Pong, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCommonServer) mustEmbedUnimplementedCommonServer() {}
func (UnimplementedCommonServer) testEmbeddedByValue()                {}

// UnsafeCommonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommonServer will
// result in compilation errors.
type UnsafeCommonServer interface {
	mustEmbedUnimplementedCommonServer()
}

func RegisterCommonServer(s grpc.ServiceRegistrar, srv CommonServer) {
	// If the following call panics, it indicates UnimplementedCommonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Common_ServiceDesc, srv)
}

func _Common_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommonServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Common_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommonServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Common_ServiceDesc is the grpc.ServiceDesc for Common service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Common_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.Common",
	HandlerType: (*CommonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Common_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver/driver.proto",
}

const (
	DriverInstanceService_DriverReg_FullMethodName        = "/driver.DriverInstanceService/DriverReg"
	DriverInstanceService_DriverHeartbeat_FullMethodName  = "/driver.DriverInstanceService/DriverHeartbeat"
	DriverInstanceService_DriverUnregister_FullMethodName = "/driver.DriverInstanceService/DriverUnregister"
)

// DriverInstanceServiceClient is the client API for DriverInstanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverInstanceServiceClient interface {
	DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error)
	DriverHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	DriverUnregister(ctx context.Context, in *DriverUnregisterRequest, opts ...grpc.CallOption) (*DriverRegResp, error)
}

type driverInstanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverInstanceServiceClient(cc grpc.ClientConnInterface) DriverInstanceServiceClient {
	return &driverInstanceServiceClient{cc}
}

func (c *driverInstanceServiceClient) DriverReg(ctx context.Context, in *DriverRegReq, opts ...grpc.CallOption) (*DriverRegResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRegResp)
	err := c.cc.Invoke(ctx, DriverInstanceService_DriverReg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverInstanceServiceClient) DriverHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, DriverInstanceService_DriverHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverInstanceServiceClient) DriverUnregister(ctx context.Context, in *DriverUnregisterRequest, opts ...grpc.CallOption) (*DriverRegResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverRegResp)
	err := c.cc.Invoke(ctx, DriverInstanceService_DriverUnregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverInstanceServiceServer is the server API for DriverInstanceService service.
// All implementations must embed UnimplementedDriverInstanceServiceServer
// for forward compatibility.
type DriverInstanceServiceServer interface {
	DriverReg(context.Context, *DriverRegReq) (*DriverRegResp, error)
	DriverHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	DriverUnregister(context.Context, *DriverUnregisterRequest) (*DriverRegResp, error)
	mustEmbedUnimplementedDriverInstanceServiceServer()
}

// UnimplementedDriverInstanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverInstanceServiceServer struct{}

func (UnimplementedDriverInstanceServiceServer) DriverReg(context.Context, *DriverRegReq) (*DriverRegResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverReg not implemented")
}
func (UnimplementedDriverInstanceServiceServer) DriverHeartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverHeartbeat not implemented")
}
func (UnimplementedDriverInstanceServiceServer) DriverUnregister(context.Context, *DriverUnregisterRequest) (*DriverRegResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverUnregister not implemented")
}
func (UnimplementedDriverInstanceServiceServer) mustEmbedUnimplementedDriverInstanceServiceServer() {}
func (UnimplementedDriverInstanceServiceServer) testEmbeddedByValue()                               {}

// UnsafeDriverInstanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverInstanceServiceServer will
// result in compilation errors.
type UnsafeDriverInstanceServiceServer interface {
	mustEmbedUnimplementedDriverInstanceServiceServer()
}

func RegisterDriverInstanceServiceServer(s grpc.ServiceRegistrar, srv DriverInstanceServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverInstanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverInstanceService_ServiceDesc, srv)
}

func _DriverInstanceService_DriverReg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverRegReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInstanceServiceServer).DriverReg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInstanceService_DriverReg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInstanceServiceServer).DriverReg(ctx, req.(*DriverRegReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverInstanceService_DriverHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInstanceServiceServer).DriverHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInstanceService_DriverHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInstanceServiceServer).DriverHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverInstanceService_DriverUnregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverInstanceServiceServer).DriverUnregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverInstanceService_DriverUnregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverInstanceServiceServer).DriverUnregister(ctx, req.(*DriverUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverInstanceService_ServiceDesc is the grpc.ServiceDesc for DriverInstanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverInstanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.DriverInstanceService",
	HandlerType: (*DriverInstanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DriverReg",
			Handler:    _DriverInstanceService_DriverReg_Handler,
		},
		{
			MethodName: "DriverHeartbeat",
			Handler:    _DriverInstanceService_DriverHeartbeat_Handler,
		},
		{
			MethodName: "DriverUnregister",
			Handler:    _DriverInstanceService_DriverUnregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver/driver.proto",
}
