// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: driver/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_driver_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{0}
}

func (x *Pong) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type DriverRegReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	DriverType    string                 `protobuf:"bytes,4,opt,name=driverType,proto3" json:"driverType,omitempty"`
	IotPlatform   string                 `protobuf:"bytes,5,opt,name=iotPlatform,proto3" json:"iotPlatform,omitempty"`
	DriverName    string                 `protobuf:"bytes,6,opt,name=driverName,proto3" json:"driverName,omitempty"`
	Extra         string                 `protobuf:"bytes,7,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegReq) Reset() {
	*x = DriverRegReq{}
	mi := &file_driver_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegReq) ProtoMessage() {}

func (x *DriverRegReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegReq.ProtoReflect.Descriptor instead.
func (*DriverRegReq) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{1}
}

func (x *DriverRegReq) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DriverRegReq) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *DriverRegReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DriverRegReq) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *DriverRegReq) GetIotPlatform() string {
	if x != nil {
		return x.IotPlatform
	}
	return ""
}

func (x *DriverRegReq) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *DriverRegReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type DriverRegResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	InstanceId    int64                  `protobuf:"varint,5,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverRegResp) Reset() {
	*x = DriverRegResp{}
	mi := &file_driver_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverRegResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverRegResp) ProtoMessage() {}

func (x *DriverRegResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverRegResp.ProtoReflect.Descriptor instead.
func (*DriverRegResp) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DriverRegResp) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DriverRegResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DriverRegResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DriverRegResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DriverRegResp) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

func (x *DriverRegResp) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_driver_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HeartbeatRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_driver_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HeartbeatResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *HeartbeatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DriverUnregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	InstanceId    int64                  `protobuf:"varint,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverUnregisterRequest) Reset() {
	*x = DriverUnregisterRequest{}
	mi := &file_driver_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverUnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverUnregisterRequest) ProtoMessage() {}

func (x *DriverUnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_driver_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverUnregisterRequest.ProtoReflect.Descriptor instead.
func (*DriverUnregisterRequest) Descriptor() ([]byte, []int) {
	return file_driver_driver_proto_rawDescGZIP(), []int{5}
}

func (x *DriverUnregisterRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *DriverUnregisterRequest) GetInstanceId() int64 {
	if x != nil {
		return x.InstanceId
	}
	return 0
}

var File_driver_driver_proto protoreflect.FileDescriptor

const file_driver_driver_proto_rawDesc = "" +
	"\n" +
	"\x13driver/driver.proto\x12\x06driver\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x04Pong\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\"\xda\x01\n" +
	"\fDriverRegReq\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\x03R\n" +
	"instanceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1e\n" +
	"\n" +
	"driverType\x18\x04 \x01(\tR\n" +
	"driverType\x12 \n" +
	"\viotPlatform\x18\x05 \x01(\tR\viotPlatform\x12\x1e\n" +
	"\n" +
	"driverName\x18\x06 \x01(\tR\n" +
	"driverName\x12\x14\n" +
	"\x05extra\x18\a \x01(\tR\x05extra\"\x9f\x01\n" +
	"\rDriverRegResp\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x05 \x01(\x03R\n" +
	"instanceId\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\"L\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\x03R\n" +
	"instanceId\"m\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"S\n" +
	"\x17DriverUnregisterRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\x03R\n" +
	"instanceId28\n" +
	"\x06Common\x12.\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\f.driver.Pong\"\x002\xeb\x01\n" +
	"\x15DriverInstanceService\x12:\n" +
	"\tDriverReg\x12\x14.driver.DriverRegReq\x1a\x15.driver.DriverRegResp\"\x00\x12H\n" +
	"\x0fDriverHeartbeat\x12\x18.driver.HeartbeatRequest\x1a\x19.driver.HeartbeatResponse\"\x00\x12L\n" +
	"\x10DriverUnregister\x12\x1f.driver.DriverUnregisterRequest\x1a\x15.driver.DriverRegResp\"\x00B4Z2github.com/lostvip-com/lv_grpc_driver_proto/driverb\x06proto3"

var (
	file_driver_driver_proto_rawDescOnce sync.Once
	file_driver_driver_proto_rawDescData []byte
)

func file_driver_driver_proto_rawDescGZIP() []byte {
	file_driver_driver_proto_rawDescOnce.Do(func() {
		file_driver_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)))
	})
	return file_driver_driver_proto_rawDescData
}

var file_driver_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_driver_driver_proto_goTypes = []any{
	(*Pong)(nil),                    // 0: driver.Pong
	(*DriverRegReq)(nil),            // 1: driver.DriverRegReq
	(*DriverRegResp)(nil),           // 2: driver.DriverRegResp
	(*HeartbeatRequest)(nil),        // 3: driver.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 4: driver.HeartbeatResponse
	(*DriverUnregisterRequest)(nil), // 5: driver.DriverUnregisterRequest
	(*emptypb.Empty)(nil),           // 6: google.protobuf.Empty
}
var file_driver_driver_proto_depIdxs = []int32{
	6, // 0: driver.Common.Ping:input_type -> google.protobuf.Empty
	1, // 1: driver.DriverInstanceService.DriverReg:input_type -> driver.DriverRegReq
	3, // 2: driver.DriverInstanceService.DriverHeartbeat:input_type -> driver.HeartbeatRequest
	5, // 3: driver.DriverInstanceService.DriverUnregister:input_type -> driver.DriverUnregisterRequest
	0, // 4: driver.Common.Ping:output_type -> driver.Pong
	2, // 5: driver.DriverInstanceService.DriverReg:output_type -> driver.DriverRegResp
	4, // 6: driver.DriverInstanceService.DriverHeartbeat:output_type -> driver.HeartbeatResponse
	2, // 7: driver.DriverInstanceService.DriverUnregister:output_type -> driver.DriverRegResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_driver_driver_proto_init() }
func file_driver_driver_proto_init() {
	if File_driver_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_driver_proto_rawDesc), len(file_driver_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_driver_driver_proto_goTypes,
		DependencyIndexes: file_driver_driver_proto_depIdxs,
		MessageInfos:      file_driver_driver_proto_msgTypes,
	}.Build()
	File_driver_driver_proto = out.File
	file_driver_driver_proto_goTypes = nil
	file_driver_driver_proto_depIdxs = nil
}
