// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: device/device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectStatus int32

const (
	ConnectStatus_OFFLINE  ConnectStatus = 0
	ConnectStatus_ONLINE   ConnectStatus = 1
	ConnectStatus_INACTIVE ConnectStatus = 2
	ConnectStatus_DISABLE  ConnectStatus = 3
	ConnectStatus_UNKNOWN  ConnectStatus = 4
)

// Enum value maps for ConnectStatus.
var (
	ConnectStatus_name = map[int32]string{
		0: "OFFLINE",
		1: "ONLINE",
		2: "INACTIVE",
		3: "DISABLE",
		4: "UNKNOWN",
	}
	ConnectStatus_value = map[string]int32{
		"OFFLINE":  0,
		"ONLINE":   1,
		"INACTIVE": 2,
		"DISABLE":  3,
		"UNKNOWN":  4,
	}
)

func (x ConnectStatus) Enum() *ConnectStatus {
	p := new(ConnectStatus)
	*p = x
	return p
}

func (x ConnectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_device_device_proto_enumTypes[0].Descriptor()
}

func (ConnectStatus) Type() protoreflect.EnumType {
	return &file_device_device_proto_enumTypes[0]
}

func (x ConnectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectStatus.Descriptor instead.
func (ConnectStatus) EnumDescriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{0}
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProductCode   string                 `protobuf:"bytes,4,opt,name=productCode,proto3" json:"productCode,omitempty"`
	DeviceCode    string                 `protobuf:"bytes,5,opt,name=deviceCode,proto3" json:"deviceCode,omitempty"`
	Secret        string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,7,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_device_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Device) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Device) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

func (x *Device) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Device) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type Request struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	TraceId    string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	DriverName string                 `protobuf:"bytes,2,opt,name=driverName,proto3" json:"driverName,omitempty"`
	// Types that are valid to be assigned to Param:
	//
	//	*Request_DeviceCode
	//	*Request_Device
	Param         isRequest_Param `protobuf_oneof:"param"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_device_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Request) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *Request) GetParam() isRequest_Param {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *Request) GetDeviceCode() string {
	if x != nil {
		if x, ok := x.Param.(*Request_DeviceCode); ok {
			return x.DeviceCode
		}
	}
	return ""
}

func (x *Request) GetDevice() *Device {
	if x != nil {
		if x, ok := x.Param.(*Request_Device); ok {
			return x.Device
		}
	}
	return nil
}

type isRequest_Param interface {
	isRequest_Param()
}

type Request_DeviceCode struct {
	DeviceCode string `protobuf:"bytes,3,opt,name=deviceCode,proto3,oneof"`
}

type Request_Device struct {
	Device *Device `protobuf:"bytes,4,opt,name=device,proto3,oneof"`
}

func (*Request_DeviceCode) isRequest_Param() {}

func (*Request_Device) isRequest_Param() {}

type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	TraceId string                 `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId,omitempty"`
	Msg     string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Code    int32                  `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Success bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Extra   string                 `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Response_Status
	//	*Response_Device
	Data          isResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_device_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *Response) GetData() isResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetStatus() ConnectStatus {
	if x != nil {
		if x, ok := x.Data.(*Response_Status); ok {
			return x.Status
		}
	}
	return ConnectStatus_OFFLINE
}

func (x *Response) GetDevice() *Device {
	if x != nil {
		if x, ok := x.Data.(*Response_Device); ok {
			return x.Device
		}
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_Status struct {
	Status ConnectStatus `protobuf:"varint,6,opt,name=status,proto3,enum=device.ConnectStatus,oneof"`
}

type Response_Device struct {
	Device *Device `protobuf:"bytes,7,opt,name=device,proto3,oneof"`
}

func (*Response_Status) isResponse_Data() {}

func (*Response_Device) isResponse_Data() {}

var File_device_device_proto protoreflect.FileDescriptor

const file_device_device_proto_rawDesc = "" +
	"\n" +
	"\x13device/device.proto\x12\x06device\"\x8b\x02\n" +
	"\x06Device\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vproductCode\x18\x04 \x01(\tR\vproductCode\x12\x1e\n" +
	"\n" +
	"deviceCode\x18\x05 \x01(\tR\n" +
	"deviceCode\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\x12/\n" +
	"\x05extra\x18\a \x03(\v2\x19.device.Device.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x01\n" +
	"\aRequest\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x1e\n" +
	"\n" +
	"driverName\x18\x02 \x01(\tR\n" +
	"driverName\x12 \n" +
	"\n" +
	"deviceCode\x18\x03 \x01(\tH\x00R\n" +
	"deviceCode\x12(\n" +
	"\x06device\x18\x04 \x01(\v2\x0e.device.DeviceH\x00R\x06deviceB\a\n" +
	"\x05param\"\xdd\x01\n" +
	"\bResponse\x12\x18\n" +
	"\atraceId\x18\x01 \x01(\tR\atraceId\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x03 \x01(\x05R\x04code\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x14\n" +
	"\x05extra\x18\x05 \x01(\tR\x05extra\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.device.ConnectStatusH\x00R\x06status\x12(\n" +
	"\x06device\x18\a \x01(\v2\x0e.device.DeviceH\x00R\x06deviceB\x06\n" +
	"\x04data*P\n" +
	"\rConnectStatus\x12\v\n" +
	"\aOFFLINE\x10\x00\x12\n" +
	"\n" +
	"\x06ONLINE\x10\x01\x12\f\n" +
	"\bINACTIVE\x10\x02\x12\v\n" +
	"\aDISABLE\x10\x03\x12\v\n" +
	"\aUNKNOWN\x10\x042\xe2\x02\n" +
	"\tRpcDevice\x12+\n" +
	"\x04Save\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x12.\n" +
	"\aConnect\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x121\n" +
	"\n" +
	"Disconnect\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x120\n" +
	"\tKeepAlive\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x120\n" +
	"\tGetStatus\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x122\n" +
	"\vQueryByCode\x12\x0f.device.Request\x1a\x10.device.Response\"\x00\x12-\n" +
	"\x06Delete\x12\x0f.device.Request\x1a\x10.device.Response\"\x00B4Z2github.com/lostvip-com/lv_grpc_driver_proto/deviceb\x06proto3"

var (
	file_device_device_proto_rawDescOnce sync.Once
	file_device_device_proto_rawDescData []byte
)

func file_device_device_proto_rawDescGZIP() []byte {
	file_device_device_proto_rawDescOnce.Do(func() {
		file_device_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_device_proto_rawDesc), len(file_device_device_proto_rawDesc)))
	})
	return file_device_device_proto_rawDescData
}

var file_device_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_device_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_device_proto_goTypes = []any{
	(ConnectStatus)(0), // 0: device.ConnectStatus
	(*Device)(nil),     // 1: device.Device
	(*Request)(nil),    // 2: device.Request
	(*Response)(nil),   // 3: device.Response
	nil,                // 4: device.Device.ExtraEntry
}
var file_device_device_proto_depIdxs = []int32{
	4,  // 0: device.Device.extra:type_name -> device.Device.ExtraEntry
	1,  // 1: device.Request.device:type_name -> device.Device
	0,  // 2: device.Response.status:type_name -> device.ConnectStatus
	1,  // 3: device.Response.device:type_name -> device.Device
	2,  // 4: device.RpcDevice.Save:input_type -> device.Request
	2,  // 5: device.RpcDevice.Connect:input_type -> device.Request
	2,  // 6: device.RpcDevice.Disconnect:input_type -> device.Request
	2,  // 7: device.RpcDevice.KeepAlive:input_type -> device.Request
	2,  // 8: device.RpcDevice.GetStatus:input_type -> device.Request
	2,  // 9: device.RpcDevice.QueryByCode:input_type -> device.Request
	2,  // 10: device.RpcDevice.Delete:input_type -> device.Request
	3,  // 11: device.RpcDevice.Save:output_type -> device.Response
	3,  // 12: device.RpcDevice.Connect:output_type -> device.Response
	3,  // 13: device.RpcDevice.Disconnect:output_type -> device.Response
	3,  // 14: device.RpcDevice.KeepAlive:output_type -> device.Response
	3,  // 15: device.RpcDevice.GetStatus:output_type -> device.Response
	3,  // 16: device.RpcDevice.QueryByCode:output_type -> device.Response
	3,  // 17: device.RpcDevice.Delete:output_type -> device.Response
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_device_device_proto_init() }
func file_device_device_proto_init() {
	if File_device_device_proto != nil {
		return
	}
	file_device_device_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_DeviceCode)(nil),
		(*Request_Device)(nil),
	}
	file_device_device_proto_msgTypes[2].OneofWrappers = []any{
		(*Response_Status)(nil),
		(*Response_Device)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_device_proto_rawDesc), len(file_device_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_device_proto_goTypes,
		DependencyIndexes: file_device_device_proto_depIdxs,
		EnumInfos:         file_device_device_proto_enumTypes,
		MessageInfos:      file_device_device_proto_msgTypes,
	}.Build()
	File_device_device_proto = out.File
	file_device_device_proto_goTypes = nil
	file_device_device_proto_depIdxs = nil
}
